sudo: required

before_install:
    - docker pull tgrogers/gpgpu-sim_regress:latest

language: cpp


matrix:
  include:
    - services: docker
      env: CONFIG=configs.gtx480.yml
# This config is just taking far too long...
#    - services: docker
#      env:
#       - CONFIG=configs.gtx750ti.yml
#       - CUDA_INSTALL_PATH=/usr/local/cuda-4.2/
    - services: docker
      env:
        - CONFIG=configs.quadro5600.yml
        - CUDA_INSTALL_PATH=/usr/local/cuda-4.2/
    - services: docker
      env:
        - CONFIG=configs.quadro5800.yml
        - CUDA_INSTALL_PATH=/usr/local/cuda-4.2/
    - services: docker
      env:
        - CONFIG=configs.teslac2050.yml
        - CUDA_INSTALL_PATH=/usr/local/cuda-4.2/
    - services: docker
      env:
        - CONFIG=configs.gtx1080ti.yml
        - CUDA_INSTALL_PATH=/usr/local/cuda-4.2/
        - PTXAS_CUDA_INSTALL_PATH=/usr/local/cuda-9.1/

script: docker run -v `pwd`:/home/runner/gpgpu-sim_distribution:rw tgrogers/gpgpu-sim_regress:latest /bin/bash -c "./start_torque.sh; chown -R runner /home/runner/gpgpu-sim_distribution; su - runner -c 'source /home/runner/gpgpu-sim_distribution/setup_environment && make -j -C /home/runner/gpgpu-sim_distribution && cd /home/runner/gpgpu-sim_simulations/ && git pull && /home/runner/gpgpu-sim_simulations/util/job_launching/run_simulations.py -c /home/runner/gpgpu-sim_simulations/util/job_launching/regression_recipies/rodinia_2.0-ft/$CONFIG -N regress && /home/runner/gpgpu-sim_simulations/util/job_launching/monitor_func_test.py -v -N regress'"
